# Generated by Django 3.2 on 2021-08-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=20)),
                ('massage', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Icecream_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('flavour', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='icecream_image')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecream_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bought_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.items')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('fullname', models.CharField(max_length=120)),
                ('mobilenumber', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=120)),
                ('home_address', models.CharField(max_length=120)),
                ('village', models.CharField(max_length=120)),
                ('landmark', models.CharField(max_length=120)),
                ('town_city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('item_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.bought_items')),
            ],
        ),
    ]
